<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls"
                    Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.MetadataControl"
                    Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.HeaderedControls"
                    Version="8.2.251219" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="AngleSharp" Version="1.8.2" />
    <PackageVersion Include="AngleSharp.Css" Version="1.1.2" />
    <PackageVersion Include="PdfPig" Version="0.1.16" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
