using DesktopGuides.Infrastructure.Reading;
using DesktopGuides.Infrastructure.Tests.Import;
using Xunit;

namespace DesktopGuides.Infrastructure.Tests.Reading;

public sealed class PdfPageTextSourceTests
{
    // pdf-long is generated by tools/p0/make_fixtures.py, which CI runs first.
    private const string Long = "generated/pdf-long.pdf";

    private static PdfPageTextSource Open(string fixture, int maxPageCharacters = PdfPageTextSource.DefaultMaxPageCharacters,
        int maxPages = PdfPageTextSource.DefaultMaxPages, long maxCharacters = PdfPageTextSource.DefaultMaxCharacters) =>
        PdfPageTextSource.Open(File.OpenRead(P0Fixtures.Resolve(fixture)), CancellationToken.None,
            maxPageCharacters, maxPages, maxCharacters);

    [Fact]
    public async Task ATaggedPageHasItsParagraph()
    {
        using PdfPageTextSource source = Open("pdf-access.pdf");

        PdfPageText page = await source.GetPageTextAsync(0, CancellationToken.None);

        Assert.Equal(1, source.PageCount);
        Assert.Contains("Tagged guide paragraph for Narrator", page.Text);
        Assert.True(page.HasLetters);
        Assert.False(page.Truncated);
    }

    [Fact]
    public async Task AScannedPageHasNoLetters()
    {
        using PdfPageTextSource source = Open("pdf-scan.pdf");

        PdfPageText page = await source.GetPageTextAsync(0, CancellationToken.None);

        Assert.False(page.HasLetters);
    }

    [Fact]
    public async Task TheLastPageOfALongDocumentHasItsOwnText()
    {
        using PdfPageTextSource source = Open(Long);

        PdfPageText page = await source.GetPageTextAsync(199, CancellationToken.None);

        Assert.Equal(200, source.PageCount);
        Assert.Contains("Desktop Guides P0 - page 200 of 200", page.Text);
    }

    [Theory]
    [InlineData(-1)]
    [InlineData(200)]
    public async Task IndexesOutsideTheDocumentThrow(int index)
    {
        using PdfPageTextSource source = Open(Long);

        await Assert.ThrowsAsync<ArgumentOutOfRangeException>(() => source.GetPageTextAsync(index, CancellationToken.None));
    }

    [Fact]
    public async Task ReadingEveryPageKeepsTheDefaultLimits()
    {
        using PdfPageTextSource source = Open(Long);
        for (int page = 0; page < source.PageCount; page++)
        {
            await source.GetPageTextAsync(page, CancellationToken.None);
        }

        Assert.Equal(PdfPageTextSource.DefaultMaxPages, source.PeakPages);
        Assert.True(source.PeakCharacters <= PdfPageTextSource.DefaultMaxCharacters);
    }

    [Fact]
    public async Task ACharacterLimitBoundsRetainedText()
    {
        // Each pdf-long page is about 35 characters, so 100 holds two pages.
        using PdfPageTextSource source = Open(Long, maxPageCharacters: 100, maxPages: 8, maxCharacters: 100);
        for (int page = 0; page < 20; page++)
        {
            await source.GetPageTextAsync(page, CancellationToken.None);
        }

        Assert.True(source.PeakCharacters <= 100);
        Assert.True(source.PeakPages < 8);
    }

    [Fact]
    public async Task ARecentPageIsServedAgainWithTheSameText()
    {
        using PdfPageTextSource source = Open(Long);
        PdfPageText first = await source.GetPageTextAsync(4, CancellationToken.None);
        await source.GetPageTextAsync(5, CancellationToken.None);

        PdfPageText again = await source.GetPageTextAsync(4, CancellationToken.None);

        Assert.Equal(first, again);
    }

    [Fact]
    public async Task LongPageTextIsTruncated()
    {
        using PdfPageTextSource source = Open("pdf-access.pdf", maxPageCharacters: 10, maxPages: 8, maxCharacters: 100);

        PdfPageText page = await source.GetPageTextAsync(0, CancellationToken.None);

        Assert.Equal(10, page.Text.Length);
        Assert.True(page.Truncated);
    }

    [Theory]
    [InlineData(0, 8, 100)]
    [InlineData(10, 0, 100)]
    [InlineData(200, 8, 100)]
    public void InvalidLimitsAreRejected(int maxPageCharacters, int maxPages, long maxCharacters)
    {
        using FileStream file = File.OpenRead(P0Fixtures.Resolve("pdf-access.pdf"));

        Assert.Throws<ArgumentOutOfRangeException>(() =>
            PdfPageTextSource.Open(file, CancellationToken.None, maxPageCharacters, maxPages, maxCharacters));
    }

    [Fact]
    public async Task ACancelledTokenStopsAnExtraction()
    {
        using PdfPageTextSource source = Open(Long);

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() =>
            source.GetPageTextAsync(10, new CancellationToken(canceled: true)));
    }

    [Fact]
    public async Task CancellingDuringAnExtractionStopsIt()
    {
        GatedStream file = new(File.ReadAllBytes(P0Fixtures.Resolve(Long)));
        using PdfPageTextSource source = PdfPageTextSource.Open(file, CancellationToken.None);
        using CancellationTokenSource cancel = new();
        file.Hold();

        Task<PdfPageText> reading = source.GetPageTextAsync(150, cancel.Token);
        Assert.True(await file.ReadSeen.WaitAsync(TimeSpan.FromSeconds(5)), "Extraction never read the file.");
        cancel.Cancel();
        file.Release();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => reading);
        PdfPageText later = await source.GetPageTextAsync(151, CancellationToken.None);
        Assert.Contains("page 152 of 200", later.Text);
    }

    [Fact]
    public async Task DisposeDuringAnExtractionWaitsForIt()
    {
        GatedStream file = new(File.ReadAllBytes(P0Fixtures.Resolve(Long)));
        PdfPageTextSource source = PdfPageTextSource.Open(file, CancellationToken.None);
        file.Hold();

        Task<PdfPageText> reading = source.GetPageTextAsync(150, CancellationToken.None);
        Assert.True(await file.ReadSeen.WaitAsync(TimeSpan.FromSeconds(5)), "Extraction never read the file.");
        Task disposing = Task.Run(source.Dispose);
        await Task.Delay(200);
        Assert.False(disposing.IsCompleted);
        Assert.False(file.Disposed);
        file.Release();

        Assert.Contains("page 151 of 200", (await reading).Text);
        await disposing;
        Assert.True(file.Disposed);
        await Assert.ThrowsAsync<ObjectDisposedException>(() => source.GetPageTextAsync(0, CancellationToken.None));
        source.Dispose();
    }

    // Blocks reads while held, so a test can pause an extraction mid-page.
    private sealed class GatedStream(byte[] bytes) : Stream
    {
        private readonly MemoryStream inner = new(bytes, writable: false);
        private readonly ManualResetEventSlim open = new(true);

        public SemaphoreSlim ReadSeen { get; } = new(0);
        public bool Disposed { get; private set; }

        public void Hold() => open.Reset();
        public void Release() => open.Set();

        public override bool CanRead => true;
        public override bool CanSeek => true;
        public override bool CanWrite => false;
        public override long Length => inner.Length;

        public override long Position
        {
            get => inner.Position;
            set => inner.Position = value;
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            Wait();
            return inner.Read(buffer, offset, count);
        }

        public override int Read(Span<byte> buffer)
        {
            Wait();
            return inner.Read(buffer);
        }

        public override int ReadByte()
        {
            Wait();
            return inner.ReadByte();
        }

        public override long Seek(long offset, SeekOrigin origin) => inner.Seek(offset, origin);
        public override void Flush() { }
        public override void SetLength(long value) => throw new NotSupportedException();
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();

        protected override void Dispose(bool disposing)
        {
            Disposed = true;
            inner.Dispose();
            base.Dispose(disposing);
        }

        private void Wait()
        {
            if (open.IsSet) return;
            ReadSeen.Release();
            open.Wait();
        }
    }
}
