"""Create deterministic, self-authored P0 reader fixtures and their manifest."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import struct
import zlib


ROOT = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "p0"
FILES: list[dict[str, object]] = []


def add(relative_path: str, data: bytes, kind: str, purpose: str) -> None:
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    FILES.append(
        {
            "id": path.stem if path.stem != "guide" else relative_path.split("/")[0],
            "path": relative_path,
            "format": kind,
            "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
            "provenance": "Generated by tools/p0/make_fixtures.py; CC0-1.0",
            "expectations": purpose,
        }
    )


def png(width: int, height: int) -> bytes:
    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + kind + data + struct.pack(
            ">I", zlib.crc32(kind + data) & 0xFFFFFFFF
        )

    row = b"\x00" + bytes((130, 176, 214, 255)) * width
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(row * height, 9))
        + chunk(b"IEND", b"")
    )


def write_pdf(objects: list[bytes], trailer_details: bytes = b"") -> bytes:
    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, body in enumerate(objects, 1):
        offsets.append(len(output))
        output.extend(f"{number} 0 obj\n".encode() + body + b"\nendobj\n")
    xref_offset = len(output)
    output.extend(f"xref\n0 {len(offsets)}\n".encode())
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010} 00000 n \n".encode())
    output.extend(
        b"trailer\n<< /Size "
        + str(len(offsets)).encode()
        + b" /Root 1 0 R"
        + trailer_details
        + b" >>\n"
        + f"startxref\n{xref_offset}\n%%EOF\n".encode()
    )
    return bytes(output)


def pdf(page_count: int) -> bytes:
    """Small PDF 1.4 writer with text on every page and correct xref offsets."""
    objects: list[bytes] = []
    pages_ref = 2
    font_ref = 3
    kids: list[int] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(b"")  # Page tree, filled after pages are appended.
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    for page_number in range(1, page_count + 1):
        page_ref = len(objects) + 1
        stream_ref = page_ref + 1
        kids.append(page_ref)
        width, height = (612, 792) if page_number % 2 else (792, 612)
        objects.append(
            (
                f"<< /Type /Page /Parent {pages_ref} 0 R "
                f"/MediaBox [0 0 {width} {height}] "
                f"/Resources << /Font << /F1 {font_ref} 0 R >> >> "
                f"/Contents {stream_ref} 0 R >>"
            ).encode()
        )
        text = f"Desktop Guides P0 - page {page_number} of {page_count}"
        commands = f"BT /F1 20 Tf 72 {height - 72} Td ({text}) Tj ET".encode()
        objects.append(
            f"<< /Length {len(commands)} >>\nstream\n".encode()
            + commands
            + b"\nendstream"
        )

    objects[1] = (
        f"<< /Type /Pages /Count {page_count} /Kids ["
        + " ".join(f"{number} 0 R" for number in kids)
        + "] >>"
    ).encode()
    return write_pdf(objects)


def tagged_pdf() -> bytes:
    """One text page with a paragraph structure element and parent tree."""
    commands = (
        b"/P <</MCID 0>> BDC\n"
        b"BT /F1 20 Tf 72 720 Td (Tagged guide paragraph for Narrator) Tj ET\n"
        b"EMC"
    )
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R /MarkInfo << /Marked true >> "
        b"/StructTreeRoot 6 0 R /Lang (en-US) >>",
        b"<< /Type /Pages /Count 1 /Kids [4 0 R] >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 3 0 R >> >> /Contents 5 0 R /StructParents 0 >>",
        f"<< /Length {len(commands)} >>\nstream\n".encode()
        + commands
        + b"\nendstream",
        b"<< /Type /StructTreeRoot /K [7 0 R] /ParentTree 9 0 R /ParentTreeNextKey 1 >>",
        b"<< /Type /StructElem /S /Document /P 6 0 R /K [8 0 R] >>",
        b"<< /Type /StructElem /S /P /P 7 0 R /Pg 4 0 R /K 0 >>",
        b"<< /Nums [0 [8 0 R]] >>",
    ]
    return write_pdf(objects)


def scanned_pdf() -> bytes:
    """A page whose visible lettering is raster pixels, with no PDF text."""
    glyphs = {
        "S": ["11111", "10000", "10000", "11111", "00001", "00001", "11111"],
        "C": ["11111", "10000", "10000", "10000", "10000", "10000", "11111"],
        "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
        "N": ["10001", "11001", "10101", "10011", "10001", "10001", "10001"],
        "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
        "L": ["10000", "10000", "10000", "10000", "10000", "10000", "11111"],
        "Y": ["10001", "10001", "01010", "00100", "00100", "00100", "00100"],
    }
    label = "SCAN ONLY"
    scale = 6
    width, height = 400, 100
    pixels = bytearray([255] * width * height)
    for letter_index, letter in enumerate(label):
        if letter == " ":
            continue
        for y, row in enumerate(glyphs[letter]):
            for x, cell in enumerate(row):
                if cell == "1":
                    for dy in range(scale):
                        for dx in range(scale):
                            px = 12 + (letter_index * 6 + x) * scale + dx
                            py = 20 + y * scale + dy
                            pixels[py * width + px] = 0
    compressed = zlib.compress(bytes(pixels), 9)
    commands = b"q 400 0 0 100 72 600 cm /Im1 Do Q"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Count 1 /Kids [3 0 R] >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /XObject << /Im1 4 0 R >> >> /Contents 5 0 R >>",
        (
            f"<< /Type /XObject /Subtype /Image /Width {width} /Height {height} "
            f"/ColorSpace /DeviceGray /BitsPerComponent 8 /Filter /FlateDecode "
            f"/Length {len(compressed)} >>\nstream\n"
        ).encode()
        + compressed
        + b"\nendstream",
        f"<< /Length {len(commands)} >>\nstream\n".encode()
        + commands
        + b"\nendstream",
    ]
    return write_pdf(objects)


PASSWORD_PADDING = bytes.fromhex(
    "28bf4e5e4e758a4164004e56fffa01082e2e00b6d0683e802f0ca9fe6453697a"
)


def pad_password(password: bytes) -> bytes:
    return (password + PASSWORD_PADDING)[:32]


def rc4(key: bytes, data: bytes) -> bytes:
    state = list(range(256))
    j = 0
    for i in range(256):
        j = (j + state[i] + key[i % len(key)]) % 256
        state[i], state[j] = state[j], state[i]
    output = bytearray()
    i = j = 0
    for value in data:
        i = (i + 1) % 256
        j = (j + state[i]) % 256
        state[i], state[j] = state[j], state[i]
        output.append(value ^ state[(state[i] + state[j]) % 256])
    return bytes(output)


def locked_pdf() -> bytes:
    """PDF Standard Security R2 fixture; test user password is 'guide'."""
    owner_key = hashlib.md5(pad_password(b"owner"), usedforsecurity=False).digest()[:5]
    owner_entry = rc4(owner_key, pad_password(b"guide"))
    document_id = hashlib.md5(
        b"desktop-guides-p0-locked", usedforsecurity=False
    ).digest()
    permissions = -4
    file_key = hashlib.md5(
        pad_password(b"guide")
        + owner_entry
        + struct.pack("<i", permissions)
        + document_id,
        usedforsecurity=False,
    ).digest()[:5]
    user_entry = rc4(file_key, PASSWORD_PADDING)
    commands = b"BT /F1 20 Tf 72 720 Td (Locked guide secret page) Tj ET"
    stream_key = hashlib.md5(
        file_key + bytes([5, 0, 0, 0, 0]), usedforsecurity=False
    ).digest()[:10]
    encrypted = rc4(stream_key, commands)
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Count 1 /Kids [4 0 R] >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 3 0 R >> >> /Contents 5 0 R >>",
        f"<< /Length {len(encrypted)} >>\nstream\n".encode()
        + encrypted
        + b"\nendstream",
        (
            f"<< /Filter /Standard /V 1 /R 2 /Length 40 /O <{owner_entry.hex()}> "
            f"/U <{user_entry.hex()}> /P {permissions} >>"
        ).encode(),
    ]
    trailer = (
        f" /Encrypt 6 0 R /ID [<{document_id.hex()}> <{document_id.hex()}>]"
    ).encode()
    return write_pdf(objects, trailer)


def main() -> None:
    add(
        "txt-utf8.txt",
        "Start\r\nCafé and 日本語\nSection 2\rFinal line\n".encode(),
        "txt",
        "UTF-8 text and mixed line endings normalize without losing characters",
    )
    add(
        "txt-bom.txt",
        b"\xef\xbb\xbf" + "BOM heading\r\nSecond line\n".encode(),
        "txt",
        "UTF-8 BOM is detected and excluded from displayed text",
    )
    add(
        "txt-legacy.txt",
        b"Guide \x82\r\nItem list\r\n",
        "txt",
        "Requires explicit CP437 selection to display e-acute",
    )
    add(
        "txt-ascii.txt",
        b"MAP\n+---+---+\n| A | B |\n+---+---+\n\n"
        b"Columns:   one     two\nVery long line: " + b"X" * 2048 + b"\n",
        "txt",
        "Preserve spaces, columns, and a horizontally overflowing line",
    )
    long_line = b"Area 001  |  Proceed north, then open the chest.  |\r\n"
    long_text = b"Desktop Guides generated long walkthrough\r\n" + long_line * (
        10 * 1024 * 1024 // len(long_line) + 1
    )
    add(
        "generated/txt-long.txt",
        long_text[: 10 * 1024 * 1024],
        "txt",
        "Large-file virtualization and locator performance",
    )

    add(
        "html-static/guide.html",
        b"""<!doctype html><html><head><meta charset="utf-8">
<link rel="stylesheet" href="styles/main.css"></head><body>
<main><h1>Guide start</h1><a href="#boss">Jump to boss</a>
<p>First section with a local map.</p><img src="images/map.png" alt="Blue map">
<div style="height:700px"></div><h2 id="boss">Boss room</h2>
<p>The unique boss room marker is here.</p></main></body></html>""",
        "html",
        "Local nested CSS and image render offline; internal anchor works",
    )
    add(
        "html-static/styles/main.css",
        b'@import "palette.css"; body { max-width: 52rem; margin: auto; color: #244; }\n',
        "css",
        "Nested relative CSS resolves locally",
    )
    add(
        "html-static/styles/palette.css",
        b"h1, h2 { color: #357; }\n",
        "css",
        "CSS import resolves locally",
    )
    add(
        "html-static/images/map.png",
        png(160, 90),
        "png",
        "Relative image renders offline",
    )
    add(
        "html-layout/guide.html",
        b"""<!doctype html><html><body><h1>Layout test</h1>
<p>Start marker</p><img src="large.png" alt="Wide chart">
<div style="height:1600px"></div><p id="resume">Resume marker after chart</p>
</body></html>""",
        "html",
        "Image dimensions and font changes must not lose the resume marker",
    )
    add(
        "html-layout/large.png",
        png(1100, 500),
        "png",
        "Large local image changes page height",
    )
    add(
        "html-hostile/guide.html",
        b"""<!doctype html><html><head>
<link rel="stylesheet" href="bad.css"></head><body><h1>Hostile resource probe</h1>
<img src="http://127.0.0.1:8765/image.png" alt="Remote image">
<iframe src="http://127.0.0.1:8765/frame"></iframe>
<form action="http://127.0.0.1:8765/form"><button>Send</button></form>
<a href="http://127.0.0.1:8765/link" target="_blank">External link</a>
<a href="file:///C:/Windows/win.ini">Absolute file</a>
<a href="../../outside.html">Parent path</a>
<script>fetch('http://127.0.0.1:8765/script')</script>
</body></html>""",
        "html",
        "Remote, active, file, and parent-path attempts are rejected",
    )
    add(
        "html-hostile/bad.css",
        b'@import url("http://127.0.0.1:8765/import.css"); '
        b'body { background-image: url("http://127.0.0.1:8765/background.png"); }\n',
        "css",
        "CSS cannot initiate remote requests",
    )
    add(
        "html-hostile/redirect.html",
        b"""<!doctype html><html><head>
<meta http-equiv="refresh" content="0;url=http://127.0.0.1:8765/redirect">
</head><body>Redirect test</body></html>""",
        "html",
        "Meta refresh cannot navigate the embedded reader to a remote origin",
    )
    add("pdf-short.pdf", pdf(2), "pdf", "Text page rendering and page-number restore")
    add(
        "generated/pdf-long.pdf",
        pdf(200),
        "pdf",
        "Many-page rendering, cache bounds, mixed page dimensions",
    )
    add(
        "pdf-access.pdf",
        tagged_pdf(),
        "pdf",
        "Tagged selectable paragraph for Narrator and PDF text-layer checks",
    )
    add(
        "pdf-scan.pdf",
        scanned_pdf(),
        "pdf",
        "Raster-only lettering must not be mistaken for selectable PDF text",
    )
    add(
        "pdf-locked.pdf",
        locked_pdf(),
        "pdf",
        "Password-protected PDF asks for a password; test password is guide",
    )

    manifest = {"schemaVersion": 1, "fixtures": FILES}
    (ROOT / "manifest.json").write_bytes(
        (json.dumps(manifest, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    )


if __name__ == "__main__":
    main()
